DROP TABLE IF EXISTS employees CASCADE;

CREATE TABLE employees (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR (255) NOT NULL,
  age INTEGER NOT NULL,
  country VARCHAR (255) NOT NULL,
  position VARCHAR (255) NOT NULL,
  wage INTEGER NOT NULL
);